### ISSUE TITLE
Tidelift

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Home#121]
@tom-englert @ltrzesniewski   I am adding Fody to tidelift. Give you are both the most regular contributors, i thought i would see if either of you would like to be involved in providing support?

**Comment by SimonCropp** [comment]
@GeertvanHorrik what do you want to do with costura in this context?

**Comment by tom-englert** [comment]
@SimonCropp what exactly does this mean? What is the impact? What about "3rd party weavers"?

**Comment by SimonCropp** [comment]
@phated i remember seeing a page that outlined the tasks of a lifter. but now i cant find it. can you help me out?

**Comment by phated** [comment]
We keep an updated list of tasks and walkthroughs for each at https://tidelift.com/about/lifter-tasks

**Comment by SimonCropp** [comment]
@tom-englert @ltrzesniewski  you dont have to decide now.

**Comment by GeertvanHorrik** [comment]
You can put costara there as well, interesting move, curious to see how all of this works

**Comment by SimonCropp** [comment]
ok i added it to all the readmes and the licensing FAQ

> **It is expected that all developers using Fody either [become a Patron on OpenCollective](https://opencollective.com/fody/), or have a [Tidelift Subscription](https://tidelift.com/subscription/pkg/nuget-fody?utm_source=nuget-fody&utm_medium=referral&utm_campaign=enterprise). [See Licensing/Patron FAQ](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md) for more information.**

also tweeted. https://twitter.com/SimonCropp/status/1222847585947275264

will close this for now. if/when any support cases come in i will let you all know they go

**Comment by SimonCropp** [comment]
@tom-englert as for "What about "3rd party weavers" i think it is the same as with opencollective patrons. they should be paying for the underlying fody usage. if an issue is specific to the 3rd party weaver, i would help fix it if it is trivial, if more complex i think the onus is on the maintainers of the 3rd party weaver to decide how to handle it

**Comment by tom-englert** [comment]
@SimonCropp can you add me as a maintainer on Tidelift?

**Comment by SimonCropp** [comment]
@phated how do i add another lifter to packages?

@tom-englert are happy to be added to all the *.Fody packages?

**Comment by tom-englert** [comment]
@SimonCropp yes, all packages will be fine

**Comment by phated** [comment]
Hey @tom-englert! You'll just need to sign up for Tidelift and sign our [Lifter Agreement](https://docs.tidelift.com/article/57-lifter-agreement). Once we have that done, I can add all the *.Fody packages to your Tidelift account.

Would this be a 50%-50% split on any income that is generated?

**Comment by tom-englert** [comment]
@tom-englert where/how do I sign this?

**Comment by tom-englert** [comment]
@phated where/how do I sign this?

**Comment by phated** [comment]
Just sign up for Tidelift and I'll email you 😁

**Comment by tom-englert** [comment]
@phated OK, signed up

**Comment by SimonCropp** [comment]
yep go with 50

**Comment by phated** [comment]
All set! Sorry for the delay here.

**Comment by SimonCropp** [comment]
@phated thanks. as an aside. how often do you re index nuget. i created a few new pages over recent weeks and they are not showing up on tidelift

**Comment by phated** [comment]
I'm not sure. There might be an issue with https://github.com/librariesio/libraries.io

**Comment by SimonCropp** [comment]
@ltrzesniewski  just double checking, you are opting out?

**Comment by ltrzesniewski** [comment]
Yes, I should have mentioned it, but I'm not interested.

**Comment by tom-englert** [comment]
@phated nearly all packages complain about "Issues affecting subscribers", which are all of type "Unlicensed packages" - however it lists just all the .Net framework assemblies (system.*, runtime.*, Microsoft.*, Netstandard.*) - this should not be an issue...

Also reading the release notes from GitHub does not work for all releases, I have tried the button "reprocess github release notes" several times, but with no success.

**Comment by phated** [comment]
Nuget support is very beta right now and their API doesn't actually return license information. Please email lift@tidelift.com to inform the rest of the team and get it resolved. Thanks.
