### ISSUE TITLE
BeforeFieldInit Fody Addin

### ISSUE THREAD

**Issue by mikernet** [Fody/Home#129]
Now that I'm firmly on the Fody train with NRT null guarding, I figured I could use it to address a few other annoyances I have 😅 I'm going to write a Fody add-in to provide control over the `beforefieldinit` flag regardless of the presence of static constructor or lack thereof. Just curious if that is something you would be interested in absorbing into your list of addins on here. I'd be happy to maintain/support it as needed.

Cheers!

**Comment by SimonCropp** [comment]
@mikernet hey. welcome aboard. seems someone else had a similar idea but abandoned it https://github.com/alexb5dh/BeforeFieldInit.Fody
