### ISSUE TITLE
nugets and open collective

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Home#175]
@ltrzesniewski @tom-englert you should not both be admins on open collective. so u can approve you own expenses.

Also i took the liberty of giving you both access to the *.fody nugets. i dont think i have been a blocker on doing nuget deployments. but figured you can both deploy now if you want to. Also the nuget download metrics can sometimes be useful when applying for jobs

**Comment by ltrzesniewski** [comment]
Thanks! And sure, you always deployed quickly, but having some backup is nice. 😄
