### ISSUE TITLE
how to handle charities

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Home#2]
i suspect the $3 per month per dev amount should be do-able for a charity. However this doesnt sit right with me, I would prefer they got to use any software they need for free. 

Ideally, in OpenCollective, we could manually add users to a given tier, and hence make them honorary patrons for a period of time. This would then make the logistics of the "everyone must be a patron and be verified" simpler.  However OpenCollective doesnt have this feature. 

As a workaround my current plan would be to donate the equivalent $ amount to them for the year, then they can be monthly patrons with that $.

**Comment by webprofusion-chrisc** [comment]
The easy solution to this might be to just maintain a google sheets list (or any other simple data store) of github usernames for everyone who has asked for a charity partonage? If you are doing any programmatic checking of usernames to flag patrons you could include this in the lookup.

**Comment by SimonCropp** [comment]
@webprofusion-chrisc how would that work when people stop working for that charity?

**Comment by webprofusion-chrisc** [comment]
I think the numbers you are likely dealing with (of charities claiming patronage) are so insignificant that any solution isn't currently worth the time it takes you to think of it/administer it. When you're making 1M a year hire someone else to solve it, until then it just doesn't matter.

**Comment by SimonCropp** [comment]
yeah will wait to see if any charities raise the issue
