### ISSUE TITLE
nugets access

### ISSUE THREAD

**Issue by tom-englert** [Fody/Home#202]
I thought about giving you the same access to my weaver projects as you did in #175, so there is a backup also for these.

While looking at nuget.org I saw that you can also add organizations there - so we could create a "Fody" organization there instead on maintaining every single package.

If you agree I would crate it and update the packages accordingly.

**Comment by SimonCropp** [comment]
sounds good to me. @ltrzesniewski ?

**Comment by ltrzesniewski** [comment]
Sure, that's a good idea. I'll add my weavers as well.

**Comment by tom-englert** [comment]
OK, I'll do it ASAP

**Comment by tom-englert** [comment]
done.
@SimonCropp there is already a "Fody" registered at gravatar.com, I assume that's yours,
so if you change the email to yours it will probably pick up the correct profile picture.
