### ISSUE TITLE
win32 dll  [DllImport("helloword.dll")]

### ISSUE THREAD

**Issue by EnhWeb** [Fody/Home#433]
win32 dll  [DllImport("helloword.dll")] OR [DllImport("helloword.so")]
helloword.dll OR helloword.so 能否也一起打包进单文件中？
helloword.dll OR helloword.so  Can they also be packaged into a single file?

**Comment by ltrzesniewski** [comment]
Duplicate of https://github.com/Fody/Costura/issues/801
