### ISSUE TITLE
if define atribute for interface its not worked for all calass that implemeted its

### ISSUE THREAD

**Issue by BQFiruz** [Fody/Home#569]
hi
if define atribute for interface its not worked for all calass that implemeted its
how can use its for interfaces

    public sealed class TransactionScopeAttribute : OnMethodBoundaryAspect
    {
        public override void OnEntry(MethodExecutionArgs args)
        {
            args.MethodExecutionTag = new TransactionScope();
        }

        public override void OnExit(MethodExecutionArgs args)
        {
            var transactionScope = (TransactionScope)args.MethodExecutionTag;

            transactionScope.Complete();
            transactionScope.Dispose();
        }

        public override void OnException(MethodExecutionArgs args)
        {
            var transactionScope = (TransactionScope)args.MethodExecutionTag;

            transactionScope.Dispose();
        }
    }
    [TransactionScope]
    public interface ISample
    {
        void Method();
    }

    public class Sample : ISample
    {
        public int id { get; set; }
        public void Method()
        {
            Debug.WriteLine("Do some database stuff isolated in surrounding transaction");
        }
    }

**Comment by ltrzesniewski** [comment]
I think your issue should be raised in the weaver repo: https://github.com/vescon/MethodBoundaryAspect.Fody

**Comment by BQFiruz** [comment]
It's not completed
It's not supported

**Comment by SimonCropp** [comment]
@BQFiruz completed is just the default behavior of github wen u close an issue. u need to raise the issue in the correct repository  https://github.com/vescon/MethodBoundaryAspect.Fody
