### ISSUE TITLE
Please remove the Patron nonsense.

### ISSUE THREAD

**Issue by varon** [Fody/Home#72]
The Patron terms are insane. The entire thing reads like a shallow cash-grab from a broke student.

If you want to earn money from your work, please use a suitable license or offer paid support. Failing any of that, just add a badge to accept donations.

This is an MIT licensed project. You should not charge people to submit a PR.

**Comment by distantcam** [comment]
@varon Please point out the part of the MIT license that requires allowing PR's for free.

**Comment by varon** [comment]
Nothing. You could just as well require a personal endorsement letter from the Dalai Lama if you wanted, but that would be weird.

This flies against the expectations and norms of an MIT licensed project.

**Comment by distantcam** [comment]
> This flies against the expectations and norms of an MIT licensed project.

And this flies against the expectations and norms of an issue. And yet you decided your opinion was worth hearing anyway. And rather than expressing a concern politely you decided to be insulting.

**Comment by varon** [comment]
Please don't perceive my directness as an insult. My intention is to share my experience of reading the Patron FAQ, which I found to be in hilariously bad taste.

**Comment by ghuntley** [comment]
Indeed, it is a MIT licensed project. It grants you freedoms to _use the software_. 

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

The license does NOT grant you freedoms to _someone's time_.

**Comment by varon** [comment]
This issue is not concerned with the license terms, but rather the social aspects and expectations surrounding the MIT license specifically. The FAQ says "If you want to help, you need to pay us.", then tries to post-hoc justify its money-grabbing via vague statements about _muh time_.

It's unbelievable that you'd try to nickle and dime people that want to make your project better.

**Comment by ghuntley** [comment]
What "social aspects and expectations surrounding the MIT license".

Link?

**Comment by varon** [comment]
Don't be obtuse for the sake of it. We both know that the vast, vast majority of MIT licensed projects do not require payment to submit a PR.

**Comment by varon** [comment]
It's already apparent that this discussion will be fruitless.

Thank you for your time.

**Comment by ghuntley** [comment]
Yet.

https://www.youtube.com/watch?v=0t85TyH-h04

**Comment by varon** [comment]
Commercial of your software was never mentioned nor planned. Only the ability to contribute help without having to pay for the privilege to do so.

**Comment by distantcam** [comment]
@varon Would you be happier if another open-source license was used instead?

**Comment by varon** [comment]
The license is absolutely perfect. Would be great if we didn't have to pay to help the project.

**Comment by mjwills** [comment]
@varon You may find reading https://twitter.com/SimonCropp/status/1166100939792474112?s=20 (ad the entire thread) of value.

**Comment by SimonCropp** [comment]
> If you want to earn money from your work, please use a suitable license or offer paid support. 

Nothing about MIT prevent a project from "strongly suggesting" that consumers pay $$.

> Failing any of that, just add a badge to accept donations.

I tried that for 12 months. approx $35 of donations were made

> This is an MIT licensed project. You should not charge people to submit a PR.... majority of MIT licensed projects do not require payment to submit a PR.

You make it sound like it costs extra $$ to raise a PR. People are expected to contribute a token amount of money to ensure the long term sustainability of the project. As it is stated in the faq "You must be a Patron to be a user of Fody. Contributing Pull Requests does not cancel this out"

What PR where you intending on submitting?

If you would like to negotiate commercial terms with a support agreement I am more than happy to enter into those negotiations.

Some history: i spent 4 years of maintaining Fody (prob a min of 5 hours a week, hard to tell really), it became clear that IL manipulation was an approach that many people wanted to take advantage of, but very few of those were comfortable to learn IL enough to contribute. I took a 6 month break to see if anyone would step up to help maintain Fody. No one did. there were just more "please fix this" and "why is this not fixed" issues. So it was either find a way that i could justify the time required, or close down the project. I tried to get sponsorship, which was not successful, so i resorted to a "token payment" model. And we are talking 3$ a month here, i chose an amount that i figured was insignificant in the scope of how much time i figured Fody was saving people.

Yes i am currently making some money out of fody. Note that the amount it is still less than minimum wage.

It should also be noted that Fody is MIT. i am more than happy for anyone to fork Fody and start a competing, and free, project.

**Comment by varon** [comment]
There's delightful irony in having commercial level support offered to you (for a price) after I've explicitly stated I have no commercial goals whatsoever.

No thank you. 

Your position is incredibly sleazy and makes you look like a total ass. May I never treat my users like you have done today.

**Comment by SimonCropp** [comment]
weather you plan to use the project commercially is not really relevant to how much time it takes to support it. i only offered you a support option since you explicitly said "please use a suitable license or offer paid support"

I am sorry you dont feel the project is worth 3$ a month to help ensure it long term maintainability.

**Comment by realvictorprm** [comment]
Well, paying for opening an issue or opening a PR for payment is the most ridiculous thing I have ever seen in the whole OSS world. Your project may be worth the 3$ per month but in my opinion with that current project attitude you will miss people which would just contribute small things to your project.

**Comment by distantcam** [comment]
> in my opinion with that current project attitude you will miss people which would just contribute small things to your project.

You'd be wrong.

**Comment by realvictorprm** [comment]
So I agree to @baron's opinion here. Sad to have such a nice project in the hand of a person which wants to take all the money.

**Comment by distantcam** [comment]
@realvictorprm How dare people get paid to do work.

**Comment by realvictorprm** [comment]
Oh yes. I do work and you get paid? No, that's not how it works.

**Comment by distantcam** [comment]
@realvictorprm You think someone opening an issue with "it broken, plz fix" is them doing work?

**Comment by realvictorprm** [comment]
Come on dont act like there are only people out there opening issues which wont be contributing to your project.

**Comment by distantcam** [comment]
@realvictorprm Ok perhaps I was a bit harsh. But most issues require some work on the part of the maintainer in order to figure out whats going on. Often an issue is presented without good reproduction steps, requiring work to figure out the error in the first place. Almost never is an issue given well, with a neat bow tie of exactly what the problem is and how to fix it. That would require the person opening the issue to do work.

Opening an issue isn't a contribution. Only after effort has been put into the issue with analysis of the code, and an explanation of what's going wrong is it then a meaningful contribution. And that effort is almost always done by the maintainer, not the contributor.

**Comment by mjwills** [comment]
Neither side of this discussion are likely to change their minds. I'd suggest everyone call it a day.

**Comment by realvictorprm** [comment]
I disagree as I can understand the reason for doing this but would prefer relaxing the rules for opening PR's and issues such that people are fine to help without paying you money. Maybe have a bounty system for issues from people which want it to be fixed?

It should be possible for both sides to move from their position slightly towards each other.
