### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Home#85]
@tom-englert @ltrzesniewski as a thanks for your ongoing help with fody. can u each put in an expense for $200 against the open collective

**Comment by ltrzesniewski** [comment]
Thanks! 😄

**Comment by tom-englert** [comment]
:smile: :smile: :smile:

**Comment by SimonCropp** [comment]
thank you both :)

and just to clear. this is a thanks for past efforts. i have no expectations on you needing to put in any extra effort going forward to justify those $

**Comment by SimonCropp** [comment]
@tom-englert @ltrzesniewski hey guys. can u invoice another 100 each

**Comment by ltrzesniewski** [comment]
Sure, thanks! 😄

**Comment by SimonCropp** [comment]
@tom-englert @ltrzesniewski  moving forward can u just invoice 100$ a month. and i will add u to the open collective so u can approve your own expenses

**Comment by tom-englert** [comment]
:smile: sure, many thanks!

**Comment by SimonCropp** [comment]
@tom-englert @ltrzesniewski lets make it 200$ a month?

**Comment by tom-englert** [comment]
Of course I wouldn't mind :smile: - however does the current budget cover this?

**Comment by SimonCropp** [comment]
@tom-englert lets see how it goes. I am going focus on some other projects for a few months. so wont be drawing from the fody budget. if there is less than 400 at the start of any month, lets discuss at that point 

BTW it doesnt hurt to remind people asking for help that they should be contributing ;)

**Comment by ltrzesniewski** [comment]
Thanks! 😄

I wasn't drawing from the budget lately either, since I haven't really contributed. But I'll keep this in mind for next time. 😉
